#
# Appveyor configuration file for CI build of SGit on Windows
#
# For further details see http://www.appveyor.com
#

#
# Install needed build dependencies
# 
install:
    - cmd: 'git submodule update --init --recursive'

#
# BUILD
#
build:
    project: SGit.sln 
    verbosity: detailed

#
# Disable tests for now
# 
test: off

#
# NOTE: Create an installation package artifact.
#
artifacts:
    - path: install
      name: SGit
      type: zip
