#
# Appveyor configuration file for CI build of SGit on Windows
#
# For further details see http://www.appveyor.com
#

#
# Environment
# 
environment:
  matrix:
    - build_version: "Debug"
    - build_version: "Release"

#
# Branches
# 
branches:
  only:
    - master

#
# OS
# 
os: Windows Server 2012 R2

#
# Install needed build dependencies
# 
install:
    - cmd: 'git submodule update --init --recursive'

#
# BUILD
#
build:
    project: SGit.sln 
#    verbosity: detailed

#
# Platform
#
platform: Any CPU

#
# Configuration
#
configuration: $env:build_version

#
# Disable tests for now
# 
test: off

#
# NOTE: Create an installation package artifact.
#
artifacts:
    - path: Run
      name: $(configuration)
      type: zip
